<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>html</string>
	</array>
	<key>name</key>
	<string>Markdown HTML</string>
	<key>scopeName</key>
	<string>source.mdhtml</string>
	<key>firstLineMatch</key>
	<string>^#+\s+</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(###) (image\-links|buttons|text\-boxes|sliders|dropdown|gallery\-block)(.*$)</string>
			<key>end</key>
			<string>(###\s*$)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>markup.list.numbered</string>
		</dict>
		
		<dict>
			<key>begin</key>
			<string>(###) (ex|exc|def|prop|thm|lem|cor|pf|ax|as)(.*$)</string>
			<key>end</key>
			<string>(###\s*$)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		
		<dict>
			<key>match</key>
			<string>(###) (banner|canvas|checkbox|desmos|nav\-buttons|wilson)\s*$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</dict>
		</dict>
		
		<dict>
			<key>match</key>
			<string>^(##) (.*$)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.heading.2.html</string>
				</dict>
			</dict>
		</dict>
		
		<dict>
			<key>match</key>
			<string>^(#) (.*$)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.heading.1.html</string>
				</dict>
			</dict>
		</dict>
		
		<dict>
			<key>begin</key>
			<string>(\$\$\s*$)</string>
			<key>end</key>
			<string>(\$\$\s*$)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>markup.raw</string>
		</dict>
		
		<dict>
			<key>begin</key>
			<string>(```)(.*$)</string>
			<key>end</key>
			<string>(```\s*$)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>markup.raw</string>
		</dict>
		
		<dict>
			<key>match</key>
			<string>(\*\*)(.+?)(\*\*)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.bold</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
			</dict>
		</dict>
		
		<dict>
			<key>match</key>
			<string>(\*)(.+?)(\*)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.italic</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
			</dict>
		</dict>
		
		<dict>
			<key>match</key>
			<string>(`)(.+?)(`)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.raw</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
			</dict>
		</dict>
		
		<dict>
			<key>match</key>
			<string>(\$)(.+?)(\$)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.raw</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
			</dict>
		</dict>
		
		<dict>
			<key>match</key>
			<string>(&lt;script.*?&lt;/script&gt;)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
			</dict>
		</dict>
	</array>
</dict>
</plist>