import { writeStateFromAscii } from "./writeStateFromArray.js";

export function expansion(gridSize)
{
	gridSize = Math.max(gridSize, 200);

	const state = new Uint8Array(gridSize * gridSize);

	const ascii = `
		..................o........
		.................ooo.......
		............ooo....oo......
		...........o..ooo..o.oo....
		..........o...o.o..o.o.....
		..........o....o.o.o.o.oo..
		............o....o.o...oo..
		oooo.o.o.o.o....o...o.ooo..
		o...o....ooo.oo.........oo.
		o.....oo...o.o.............
		.o..o....oo...oo...........
		........oo.o.o.o.o.o.o.oooo
		.o..o....oo..o..oo....o...o
		o.....oo...o.o.o...oo.....o
		o...o....oo..o..oo....o..o.
		oooo.o.o.o.o.o.o.oo........
		...........oo...oo....o..o.
		.............o.o...oo.....o
		.oo.........oo.ooo....o...o
		..ooo.o...o....o.o.o.o.oooo
		..oo...o.o....o............
		..oo.o.o.o.o....o..........
		.....o.o..o.o...o..........
		....oo.o..ooo..o...........
		......oo....ooo............
		.......ooo.................
		........o..................	
	`;

	writeStateFromAscii({
		state,
		gridSize,
		ascii
	});

	return [state, gridSize];
}