import{changeOpacity,opacityAnimationTime}from"./animation.min.mjs";import{$,addStyle,pageElement,pageUrl}from"./main.min.mjs";import anime from"/scripts/anime.min.js";let bannerElement=null;function setBannerElement(newBannerElement){bannerElement=newBannerElement}let contentElement=null;function setContentElement(newContentElement){contentElement=newContentElement}let bannerMaxScroll=null;function setBannerMaxScroll(newBannerMaxScroll){bannerMaxScroll=newBannerMaxScroll}let scrollButtonElement,scrollButtonOpacity=0,scrollButtonExists=!1;function setScrollButtonExists(newScrollButtonExists){scrollButtonExists=newScrollButtonExists}let bannerOpacity=1,lastBannerOpacityTimestamp=-1;function updateBannerOpacity(timestamp){var e,n=timestamp-lastBannerOpacityTimestamp;bannerElement&&contentElement&&timestamp!==lastBannerOpacityTimestamp&&-1!==lastBannerOpacityTimestamp?(lastBannerOpacityTimestamp=timestamp,e=1-window.scrollY/bannerMaxScroll,n=.085*n/6.944,bannerOpacity=Math.min(Math.max(Math.max(bannerOpacity-n,0),e),Math.min(bannerOpacity+n,1)),bannerElement&&(bannerElement.style.opacity=bannerOpacity),contentElement&&(contentElement.style.opacity=1-bannerOpacity),scrollButtonOpacity=Math.min(Math.max(1-window.scrollY/(bannerMaxScroll/2.5),0),1),scrollButtonExists&&0===(scrollButtonElement.style.opacity=scrollButtonOpacity)&&(scrollButtonExists=!1,scrollButtonElement.remove())):lastBannerOpacityTimestamp=timestamp,window.requestAnimationFrame(updateBannerOpacity)}window.requestAnimationFrame(updateBannerOpacity);let bannerFilename="",bannerFilepath="";const bannerPages=["/home/","/about/","/writing/mist/","/writing/desolation-point/"],multibannerPages={"/home/":{currentBanner:Math.floor(11*Math.random())+1,numBanners:11}};async function loadBanner(large=!1){if(bannerPages.includes(pageUrl)){bannerElement=$("#banner"),contentElement=$("#content"),bannerFilename=`${large?"large":"small"}.webp`,bannerFilepath=pageUrl+"banners/",pageUrl in multibannerPages&&(bannerFilepath+=multibannerPages[pageUrl].currentBanner+"/"),addStyle(`
		#banner-small
		{
			background: url(${bannerFilepath}small.webp) no-repeat center center;
			background-size: cover;
		}
		
		#banner-large
		{
			background: url(${bannerFilepath}large.webp) no-repeat center center;
			background-size: cover;
		}
	`),await fetch(bannerFilepath+bannerFilename);const n=new Image;var e=new Promise(resolve=>{n.onload=()=>{n.remove(),large||setTimeout(()=>insertScrollButton(),2e3),resolve()}});n.style.opacity=0,n.style.position="fixed",n.style.top="-100vh",n.style.left="-100vw",pageElement.appendChild(n),setTimeout(()=>{n.src=bannerFilepath+bannerFilename},20),await e}}function setUpBanner(){bannerPages.includes(pageUrl)?loadBanner(!0).then(()=>{changeOpacity($("#banner-small"),0,700).then(()=>$("#banner-small").remove())}):bannerElement=null}function insertScrollButton(){var e;window.scrollY>bannerMaxScroll/2.5||(e=document.querySelector("#banner-cover"))&&(e.insertAdjacentHTML("beforebegin",`
		<div id="new-banner-cover">
			<input type="image" id="scroll-button" src="/graphics/general-icons/chevron-down.png" style="opacity: 0" alt="Scroll down">
		</div>
	`),setTimeout(()=>{var e=$("#new-banner-cover");e&&(scrollButtonElement=$("#scroll-button"),e.style.opacity=0,e.style.transform="translateY(-100px)",anime({targets:e,opacity:1,translateY:0,duration:4*opacityAnimationTime,easing:"easeOutCubic"}),anime({targets:scrollButtonElement,opacity:scrollButtonOpacity,duration:4*opacityAnimationTime,easing:"easeOutCubic"}),setTimeout(()=>scrollButtonExists=!0,4*opacityAnimationTime))},100),document.querySelector("#banner-cover").remove())}export{bannerElement,setBannerElement,contentElement,setContentElement,bannerMaxScroll,setBannerMaxScroll,scrollButtonOpacity,scrollButtonExists,setScrollButtonExists,bannerOpacity,updateBannerOpacity,bannerPages,multibannerPages,loadBanner,setUpBanner,insertScrollButton};