import{changeOpacity,opacityAnimationTime}from"./animation.min.mjs";import{$,addStyle,pageElement,pageScroll,pageUrl,setPageScroll}from"./main.min.mjs";import anime from"/scripts/anime.min.js";let bannerElement=null;function setBannerElement(newBannerElement){bannerElement=newBannerElement}let contentElement=null;function setContentElement(newContentElement){contentElement=newContentElement}let bannerOpacity=1,bannerOpacityChange=0;const maxSingleFrameChange=.025;function setBannerOpacity(newBannerOpacity){bannerOpacityChange+=newBannerOpacity-bannerOpacity;var n=Math.min(Math.max(bannerOpacityChange,-maxSingleFrameChange),maxSingleFrameChange);bannerOpacity=Math.min(Math.max(bannerOpacity+n,0),1),bannerElement&&(bannerElement.style.opacity=bannerOpacity),contentElement&&(contentElement.style.opacity=1-bannerOpacity),bannerOpacityChange-=n,.001<Math.abs(bannerOpacityChange)&&window.requestAnimationFrame(()=>setBannerOpacity(bannerOpacity))}let bannerMaxScroll=null;function setBannerMaxScroll(newBannerMaxScroll){bannerMaxScroll=newBannerMaxScroll}let bannerFilename="",bannerFilepath="",lastScrollTimestamp=-1;const bannerPages=["/home/","/about/","/writing/mist/","/writing/desolation-point/"],multibannerPages={"/home/":{currentBanner:Math.floor(11*Math.random())+1,numBanners:11}};let scrollButtonElement,scrollButtonOpacity=0,scrollButtonExists=!1;function setScrollButtonExists(newScrollButtonExists){scrollButtonExists=newScrollButtonExists}async function loadBanner(large=!1){if(bannerPages.includes(pageUrl)){bannerElement=$("#banner"),contentElement=$("#content"),bannerFilename=`${large?"large":"small"}.webp`,bannerFilepath=pageUrl+"banners/",pageUrl in multibannerPages&&(bannerFilepath+=multibannerPages[pageUrl].currentBanner+"/"),addStyle(`
		#banner-small
		{
			background: url(${bannerFilepath}small.webp) no-repeat center center;
			background-size: cover;
		}
		
		#banner-large
		{
			background: url(${bannerFilepath}large.webp) no-repeat center center;
			background-size: cover;
		}
	`),await fetch(bannerFilepath+bannerFilename);const e=new Image;var n=new Promise(resolve=>{e.onload=()=>{e.remove(),large||setTimeout(()=>insertScrollButton(),2e3),resolve()}});e.style.opacity=0,e.style.position="fixed",e.style.top="-100vh",e.style.left="-100vw",pageElement.appendChild(e),setTimeout(()=>{e.src=bannerFilepath+bannerFilename},20),await n}}function setUpBanner(){bannerPages.includes(pageUrl)?loadBanner(!0).then(()=>{changeOpacity($("#banner-small"),0,700).then(()=>$("#banner-small").remove())}):bannerElement=null}function bannerOnScroll(scrollPositionOverride){setPageScroll(0===scrollPositionOverride?window.scrollY:scrollPositionOverride),window.requestAnimationFrame(scrollAnimationFrame)}function scrollAnimationFrame(timestamp){var n=timestamp-lastScrollTimestamp;lastScrollTimestamp=timestamp,0!=n&&scrollHandler()}function scrollHandler(){bannerElement&&contentElement&&(setBannerOpacity(1-pageScroll/bannerMaxScroll),bannerElement.style.opacity=bannerOpacity,contentElement.style.opacity=1-bannerOpacity,scrollButtonOpacity=Math.min(Math.max(1-pageScroll/(bannerMaxScroll/2.5),0),1),scrollButtonExists)&&0===(scrollButtonElement.style.opacity=scrollButtonOpacity)&&(scrollButtonExists=!1,scrollButtonElement.remove())}function insertScrollButton(){var n;pageScroll>bannerMaxScroll/2.5||(n=document.querySelector("#banner-cover"))&&(n.insertAdjacentHTML("beforebegin",`
		<div id="new-banner-cover">
			<input type="image" id="scroll-button" src="/graphics/general-icons/chevron-down.png" style="opacity: 0" alt="Scroll down">
		</div>
	`),setTimeout(()=>{var n=$("#new-banner-cover");n&&(scrollButtonElement=$("#scroll-button"),n.style.opacity=0,n.style.transform="translateY(-100px)",anime({targets:n,opacity:1,translateY:0,duration:4*opacityAnimationTime,easing:"easeOutCubic"}),anime({targets:scrollButtonElement,opacity:scrollButtonOpacity,duration:4*opacityAnimationTime,easing:"easeOutCubic"}),setTimeout(()=>scrollButtonExists=!0,4*opacityAnimationTime))},100),document.querySelector("#banner-cover").remove())}export{bannerElement,setBannerElement,contentElement,setContentElement,bannerOpacity,setBannerOpacity,bannerMaxScroll,setBannerMaxScroll,bannerPages,multibannerPages,scrollButtonOpacity,scrollButtonExists,setScrollButtonExists,loadBanner,setUpBanner,bannerOnScroll,insertScrollButton};