let bannerElement=null;function setBannerElement(e){bannerElement=e}let contentElement=null;function setContentElement(e){contentElement=e}let bannerDoneLoading=!1;function setBannerDoneLoading(e){bannerDoneLoading=e}let bannerOpacity=1;function setBannerOpacity(e){bannerOpacity=e;try{bannerElement.style.opacity=bannerOpacity,contentElement.style.opacity=1-bannerOpacity}catch(e){}bannerDoneLoading=!bannerOpacity}let bannerMaxScroll=null;function setBannerMaxScroll(e){bannerMaxScroll=e}let bannerFilename="",bannerFilepath="",lastScrollTimestamp=-1;const bannerPages=["/home/","/about/","/writing/mist/","/writing/desolation-point/"],multibannerPages={"/home/":{currentBanner:Math.floor(11*Math.random())+1,numBanners:11}},pagesAlreadyFetched=[],otherSizePagesAlreadyFetched=[];let scrollButtonExists=!1,scrollButtonTimeoutId=null,scrollButtonDoneLoading=!1;function setScrollButtonDoneLoading(e){scrollButtonDoneLoading=e}function loadBanner(a=!1){return new Promise((t,e)=>{bannerPages.includes(Page.url)||t(),bannerElement=$("#banner"),contentElement=$("#content"),bannerFilename=`${a?"large":"small"}.webp`,bannerFilepath=Page.parentFolder+"banners/",multibannerPages.hasOwnProperty(Page.url)&&(bannerFilepath+=multibannerPages[Page.url].currentBanner+"/"),Site.addStyle(`
			#banner-small
			{
				background: url(${bannerFilepath}small.webp) no-repeat center center;
				background-size: cover;
			}
			
			#banner-large
			{
				background: url(${bannerFilepath}large.webp) no-repeat center center;
				background-size: cover;
			}
		`),fetch(bannerFilepath+bannerFilename).then(e=>{const n=new Image;n.onload=()=>{n.remove(),a||(scrollButtonTimeoutId=setTimeout(()=>{insertScrollButton()},2e3)),t()},n.style.opacity=0,n.style.position="fixed",n.style.top="-100vh",n.style.left="-100vw",Page.element.appendChild(n),setTimeout(()=>{n.src=bannerFilepath+bannerFilename},20)}).catch(e=>{$("#banner").remove(),$("#banner-cover").remove(),t()})})}function bannerOnScroll(e){0===e?Page.scroll=window.scrollY:(Page.scroll=e,bannerDoneLoading=!1,scrollButtonDoneLoading=!1),window.requestAnimationFrame(scrollAnimationFrame)}function scrollAnimationFrame(e){var n=e-lastScrollTimestamp;lastScrollTimestamp=e,0!=n&&scrollHandler()}function scrollHandler(){if(Page.scroll<=bannerMaxScroll){bannerOpacity=Math.min(Math.max(1-Page.scroll/bannerMaxScroll,0),1);try{bannerElement.style.opacity=bannerOpacity,contentElement.style.opacity=1-bannerOpacity}catch(e){}bannerDoneLoading=0===bannerOpacity}else if(!bannerDoneLoading){bannerOpacity=0;try{bannerElement.style.opacity=0,contentElement.style.opacity=1}catch(e){}bannerDoneLoading=!0}if(Page.scroll<=bannerMaxScroll/2.5){var e=Math.min(Math.max(1-Page.scroll/(bannerMaxScroll/2.5),0),1);if(scrollButtonExists)try{$("#scroll-button").style.opacity=e}catch(e){}try{$("#cruz-text").parentNode.style.opacity=e,$("#godar-text").parentNode.style.opacity=e}catch(e){}scrollButtonDoneLoading=0===e}else if(scrollButtonDoneLoading)try{document.querySelector("#scroll-button").remove()}catch(e){}else{try{$("#cruz-text").parentNode.style.opacity=0,$("#godar-text").parentNode.style.opacity=0}catch(e){}try{$("#scroll-button").style.opacity=0}catch(e){}scrollButtonDoneLoading=!0}}function fetchOtherPageBannersInBackground(){$$("a").forEach(n=>{n=n.getAttribute("href");if(bannerPages.includes(n)&&!pagesAlreadyFetched.includes(n)){pagesAlreadyFetched.push(n);let e=n.slice(0,n.lastIndexOf("/")+1)+"banners/";multibannerPages.hasOwnProperty(n)&&(e+=multibannerPages[n].currentBanner+1+"/"),e+="small.webp"}})}function insertScrollButton(){if(!(Page.scroll>bannerMaxScroll/2.5)){const n=Math.min(Math.max(1-Page.scroll/(bannerMaxScroll/2.5),0),1);let e="chevron-down";1===Site.Settings.urlVars.contrast&&(e+="-dark");try{document.querySelector("#banner-cover").insertAdjacentHTML("beforebegin",`
			<div id="new-banner-cover">
				<input type="image" id="scroll-button" src="/graphics/general-icons/${e}.png" style="opacity: 0" alt="Scroll down">
			</div>
		`),setTimeout(()=>{$("#new-banner-cover").style.opacity=0,$("#new-banner-cover").style.transform="translateY(-100px)",anime({targets:$("#new-banner-cover"),opacity:1,translateY:0,duration:4*Site.opacityAnimationTime,easing:"easeOutCubic"}),anime({targets:$("#scroll-button"),opacity:n,translateY:0,duration:4*Site.opacityAnimationTime,easing:"easeOutCubic"}),setTimeout(()=>scrollButtonExists=!0,4*Site.opacityAnimationTime);try{Page.Load.HoverEvents.addWithScale(document.querySelector("#scroll-button"),1.1)}catch(e){}},100),document.querySelector("#banner-cover").remove()}catch(e){}}}function setScrollButtonExists(e){scrollButtonExists=e}export{bannerElement,setBannerElement,contentElement,setContentElement,bannerDoneLoading,setBannerDoneLoading,bannerOpacity,setBannerOpacity,bannerMaxScroll,setBannerMaxScroll,bannerPages,multibannerPages,setScrollButtonDoneLoading,loadBanner,bannerOnScroll,fetchOtherPageBannersInBackground,insertScrollButton,setScrollButtonExists};